// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

export interface PersonSchema {
  /**
   * Age in years which must be equal to or greater than zero.
   */
  age?: number
  /**
   * The person's first name.
   */
  firstName?: string
  /**
   * The person's last name.
   */
  lastName?: string
}
